### ISSUE TITLE
Create ```home``` template

### ISSUE THREAD

**Issue by miguel-merlin** [stevensblueprint/blueprint_website#22]
## Description
In the ```layouts``` folder add ```home.njk``` with the template for the home page. The template should include the following sections: 
- Tech for Social Good
- About us
- Our projects
- Get involved
- Non Profit organizations
- Contact us

## Example of template
```
<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
  </head>

  <body>
    <main>
      {{ content | safe }}
    </main>
  </body>
</html>
```

## Currently blocked by
#41 , #24

**Comment by aidanouckama** [comment]
I would like to take on this task.

**Comment by ezrizhu** [comment]
thank you, i have assigned you to this issue.
