### ISSUE TITLE
Non Profit Organizations - Our Project Timeline

### ISSUE THREAD

**Issue by Caposto** [stevensblueprint/blueprint_website#223]
# Description

On the `community/organizations` route, implement the following designs and content:

![Image](https://github.com/user-attachments/assets/1b95cc2f-9b48-45c0-8c86-f56f0bea996b)

# Definition of Done
- [ ] Designs are implemented above
- [ ] Create a component that isolates the work on this section of the page

**Comment by ShawnAviles** [comment]
Closed with #230
