### ISSUE TITLE
Create ```footer``` component

### ISSUE THREAD

**Issue by miguel-merlin** [stevensblueprint/blueprint_website#26]
## Description
Create a React-like component that renders a member card (Footer.jsx). The card should include the following: 
- Blueprint Logo
- General
  - About 
  - Team
  - Projects
  - Contact
  - Blog 
-  Students
  - Apply
  - Process
  - FAQs
- Nonprofits
  - Apply
  - Process 
  - FAQs
- Social Media
  - LinkedIn
  - Github

Add the Footer component  in ```_components``` directory. Remeber to add the component to the ```_config.ts``` 

```
site.component("ui", {
  name: "button",
  css: ".btn { background: blue; color: white }",
  render({ text }) {
    return `<button class="btn">${text}</button>`;
  },
});
```

## Example
![image](https://github.com/stevensblueprint/blueprint_website/assets/106508795/49d3a972-dd43-4e9f-af42-d7362cd05b20)

**Comment by ShawnAviles** [comment]
@Lucasha11 I updated your branch so you can see your changes and run it all locally. Best of luck with the rest of your first task!
