### ISSUE TITLE
Create `blog` template (blog post page)

### ISSUE THREAD

**Issue by miguel-merlin** [stevensblueprint/blueprint_website#39]
## Description 
In the ```layouts``` folder add ```blog.njk``` with the template for a blog. The template should include the following.
- Title of blog
- Content of blog

## Examples
https://medium.com/blueprint/vouchers-4-veggies-a-project-overview-a81a28a22134

https://ericz.me/blog/cloud-vnc-proxy

**Comment by ShawnAviles** [comment]
Reopening to create Blog **Post** template for first Blog Post
